#!/usr/bin/env bash
# Matched-budget GRPO sweep for Qwen2.5-3B-Instruct on multi-problem GSM8K.
#
# Run from the repository root after prepare_data.py:
#   K=4 DATA_DIR=/path/to/data bash examples/multi_problem_gsm8k/run_qwen2_5_3b_grpo.sh

set -euo pipefail
set -x

K=${K:?Set K to one of the prompt sizes generated by prepare_data.py.}
case "${K}" in
    1|2|4|8) ;;
    *) echo "K must be one of 1, 2, 4, or 8; got ${K}." >&2; exit 2 ;;
esac

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
DATA_DIR=${DATA_DIR:?Set DATA_DIR to the output of prepare_data.py.}
MODEL_PATH=${MODEL_PATH:-Qwen/Qwen2.5-3B-Instruct}
PROJECT_NAME=${PROJECT_NAME:-multi-problem-gsm8k}
EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen2_5_3b-grpo-k${K}}
CHECKPOINT_DIR=${CHECKPOINT_DIR:-${REPO_ROOT}/checkpoints/${PROJECT_NAME}/${EXPERIMENT_NAME}}
RAY_TMPDIR=${RAY_TMPDIR:-/tmp/${USER}/ray-${EXPERIMENT_NAME}}

# Each update contains the same number of underlying GSM8K problems for every
# K. Since each prompt is sampled ROLLOUT_N times, this also matches the number
# of per-problem rollout samples up to EOS behavior.
BASE_PROBLEMS_PER_UPDATE=${BASE_PROBLEMS_PER_UPDATE:-128}
if (( BASE_PROBLEMS_PER_UPDATE % K != 0 )); then
    echo "BASE_PROBLEMS_PER_UPDATE=${BASE_PROBLEMS_PER_UPDATE} must be divisible by K=${K}." >&2
    exit 2
fi
TRAIN_BATCH_SIZE=$((BASE_PROBLEMS_PER_UPDATE / K))
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-${TRAIN_BATCH_SIZE}}

PER_PROBLEM_MAX_PROMPT_LENGTH=${PER_PROBLEM_MAX_PROMPT_LENGTH:-512}
PER_PROBLEM_MAX_RESPONSE_LENGTH=${PER_PROBLEM_MAX_RESPONSE_LENGTH:-512}
MAX_PROMPT_LENGTH=$((PER_PROBLEM_MAX_PROMPT_LENGTH * K))
MAX_RESPONSE_LENGTH=$((PER_PROBLEM_MAX_RESPONSE_LENGTH * K))
MAX_MODEL_LENGTH=$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))

ROLLOUT_N=${ROLLOUT_N:-8}
NGPUS_PER_NODE=${NGPUS_PER_NODE:-2}
ACTOR_LR=${ACTOR_LR:-1e-6}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-4}
TEST_FREQ=${TEST_FREQ:-10}
SAVE_FREQ=${SAVE_FREQ:-29}
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.70}

TRAIN_FILE=${TRAIN_FILE:-${DATA_DIR}/train_k${K}.parquet}
VAL_FILE=${VAL_FILE:-${DATA_DIR}/val_all.parquet}
REWARD_PATH=${REWARD_PATH:-${REPO_ROOT}/examples/multi_problem_gsm8k/reward.py}

for required_file in "${TRAIN_FILE}" "${VAL_FILE}" "${REWARD_PATH}"; do
    if [[ ! -f "${required_file}" ]]; then
        echo "Required file not found: ${required_file}" >&2
        exit 2
    fi
done

mkdir -p "${CHECKPOINT_DIR}" "${RAY_TMPDIR}"
export RAY_TMPDIR

cd "${REPO_ROOT}"
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.use_kl_in_reward=False \
    data.train_files="${TRAIN_FILE}" \
    data.val_files="${VAL_FILE}" \
    data.train_batch_size=${TRAIN_BATCH_SIZE} \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.filter_overlong_prompts=True \
    data.truncation=error \
    data.seed=42 \
    reward.custom_reward_function.path="${REWARD_PATH}" \
    reward.custom_reward_function.name=compute_score \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_remove_padding=True \
    +actor_rollout_ref.model.override_config.attn_implementation=eager \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.optim.lr=${ACTOR_LR} \
    actor_rollout_ref.actor.ppo_mini_batch_size=${PPO_MINI_BATCH_SIZE} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.ref.strategy=fsdp \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.n=${ROLLOUT_N} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=${GPU_MEMORY_UTILIZATION} \
    actor_rollout_ref.rollout.max_model_len=${MAX_MODEL_LENGTH} \
    actor_rollout_ref.rollout.max_num_batched_tokens=${MAX_MODEL_LENGTH} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.free_cache_engine=True \
    trainer.logger='["console","wandb"]' \
    trainer.project_name="${PROJECT_NAME}" \
    trainer.experiment_name="${EXPERIMENT_NAME}" \
    trainer.n_gpus_per_node=${NGPUS_PER_NODE} \
    trainer.nnodes=1 \
    trainer.total_epochs=${TOTAL_EPOCHS} \
    trainer.test_freq=${TEST_FREQ} \
    trainer.save_freq=${SAVE_FREQ} \
    trainer.default_local_dir="${CHECKPOINT_DIR}" \
    trainer.val_before_train=True \
    trainer.resume_mode=disable \
    ray_kwargs.ray_init.runtime_env.py_executable=null \
    "$@"
